# Generated by Django 4.2.19 on 2025-12-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='text_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_es',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_es',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_es',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_es',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
