# Generated by Django 4.2.27 on 2025-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_achievement_text_en_achievement_text_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(max_length=200),
        ),
    ]
