# Generated by Django 4.2.27 on 2025-12-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_end_period_experience_start_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='period',
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_period',
            field=models.DateField(),
        ),
    ]
