# Generated by Django 4.2.27 on 2026-01-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_es',
            field=models.TextField(blank=True),
        ),
    ]
