# Generated by Django 4.2.19 on 2026-01-08 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_certification_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_es', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', unique=True)),
                ('content', models.TextField(help_text='Full article content')),
                ('content_en', models.TextField(blank=True)),
                ('content_es', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listing page')),
                ('excerpt_en', models.TextField(blank=True)),
                ('excerpt_es', models.TextField(blank=True)),
                ('author', models.CharField(default='Piettro Rodrigues', max_length=100)),
                ('published_date', models.DateField()),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('featured', models.BooleanField(default=False, help_text='Show in homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-star', help_text='Font Awesome icon class', max_length=100)),
                ('icon_bg_color', models.CharField(default='accent-purple/20', help_text='Icon background color class', max_length=50)),
                ('icon_color', models.CharField(default='accent-purple', help_text='Icon color class', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Core Competency',
                'verbose_name_plural': 'Core Competencies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('icon_color', models.CharField(default='blue-400', help_text='Icon color class', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience Technology',
                'verbose_name_plural': 'Experience Technologies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('image_url', models.URLField(help_text='URL for hobby image')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobbies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('icon_color', models.CharField(blank=True, help_text='Icon color or class', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Technology',
                'verbose_name_plural': 'Project Technologies',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-order'], 'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-order'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order'], 'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certification',
            name='icon',
            field=models.CharField(default='fas fa-certificate', help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='icon_bg_color',
            field=models.CharField(default='bg-accent-purple/20', help_text='Icon background color class', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.CharField(blank=True, help_text='Single character or icon code for logo', max_length=10),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_logo_bg',
            field=models.CharField(default='bg-blue-600', help_text='Tailwind bg color class', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.CharField(default='fas fa-briefcase', help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='icon_color',
            field=models.CharField(default='accent-purple', help_text='Icon color class', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_type',
            field=models.CharField(default='On-site', help_text='On-site, Remote, Hybrid', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in first 6 projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_bg_gradient',
            field=models.CharField(blank=True, help_text='Tailwind gradient classes', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_text',
            field=models.CharField(blank=True, help_text='Text to show if no logo URL', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL for project logo/icon'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('data-science', 'Data Science'), ('web', 'Web Development'), ('mobile', 'Mobile Development'), ('ml', 'Machine Learning'), ('ai', 'Artificial Intelligence')], default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='experience_years',
            field=models.CharField(blank=True, help_text="e.g., '2y+', '3y+', 'Current'", max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Icon color or class', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=0, help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='icon',
            field=models.CharField(default='fas fa-code', help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='projecttechnology',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='experiencetechnology',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.experience'),
        ),
    ]
