# Generated by Django 4.2.19 on 2026-01-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_blogpost_corecompetency_experiencetechnology_hobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Problems and challenges faced in the project'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions',
            field=models.TextField(blank=True, help_text='How the problems were solved'),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_es',
            field=models.TextField(blank=True),
        ),
    ]
