# Generated by Django 4.2.19 on 2026-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_challenges_project_challenges_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, help_text='Description for homepage card (uses excerpt if empty)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL for blog post featured image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.URLField(blank=True, help_text='Link to full article'),
        ),
    ]
