# Generated by Django 4.2.27 on 2026-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_blogpost_description_blogpost_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_logo_image',
            field=models.URLField(blank=True, help_text='URL for company logo image'),
        ),
    ]
