# Generated by Django 4.2.27 on 2026-01-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_experience_company_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_logo_bg',
        ),
    ]
