# Generated by Django 4.2.27 on 2026-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_experience_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencetechnology',
            name='icon_color',
        ),
        migrations.AlterField(
            model_name='experiencetechnology',
            name='icon',
            field=models.URLField(blank=True, help_text='URL for logo image'),
        ),
    ]
