# Generated by Django 4.2.27 on 2026-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_experiencetechnology_icon_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_color',
        ),
        migrations.AddField(
            model_name='experiencetechnology',
            name='icon_color',
            field=models.CharField(default='blue-400', help_text='Icon color class', max_length=50),
        ),
        migrations.AlterField(
            model_name='experiencetechnology',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.URLField(blank=True, help_text='URL for logo image'),
        ),
    ]
